_name_or_path:
    value: microsoft/mdeberta-v3-base
_wandb:
    value:
        cli_version: 0.23.1
        e:
            6rc29weu35kix1dn35pgnzxx2gwg0eff:
                codePath: src/training/trainer.py
                codePathLocal: src/training/trainer.py
                cpu_count: 14
                cpu_count_logical: 28
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "429287014400"
                        used: "255256948736"
                email: gabrieledurante01@gmail.com
                executable: /home/gabriele/Github/NerGuard/.venv/bin/python3
                git:
                    commit: ad16938b4daab437ff493603a347659f8e16c42f
                    remote: https://github.com/exdsgift/NerGuard.git
                gpu: Quadro RTX 6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-ca6c1987-a959-7f45-6559-bd21ca6bc893
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-3e231e07-0e97-e8e1-b350-ecf7c8f33865
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-890f7224-fd70-336d-b428-a6bcd1de8beb
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-a03c018d-3d8d-04b0-8223-22756be8fc1a
                host: memphis
                memory:
                    total: "67087441920"
                os: Linux-5.4.0-204-generic-x86_64-with-glibc2.31
                program: /home/gabriele/Github/NerGuard/./src/training/trainer.py
                python: CPython 3.11.13
                root: /home/gabriele/Github/NerGuard
                slurm:
                    root: /opt/slurm/19.05.6
                startedAt: "2025-12-06T06:07:15.185193Z"
                writerId: 6rc29weu35kix1dn35pgnzxx2gwg0eff
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 7
                - 19
                - 66
            "4": 3.11.13
            "5": 0.23.1
            "6": 4.57.0
            "9":
                "1": transformers_trainer
            "12": 0.23.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value: null
attention_probs_dropout_prob:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: float32
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 500
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 768
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": O
        "1": B-AGE
        "2": B-BUILDINGNUM
        "3": B-CITY
        "4": B-CREDITCARDNUMBER
        "5": B-DATE
        "6": B-DRIVERLICENSENUM
        "7": B-EMAIL
        "8": B-GENDER
        "9": B-GIVENNAME
        "10": B-IDCARDNUM
        "11": B-PASSPORTNUM
        "12": B-SEX
        "13": B-SOCIALNUM
        "14": B-STREET
        "15": B-SURNAME
        "16": B-TAXNUM
        "17": B-TELEPHONENUM
        "18": B-TIME
        "19": B-TITLE
        "20": B-ZIPCODE
        "21": I-AGE
        "22": I-BUILDINGNUM
        "23": I-CITY
        "24": I-CREDITCARDNUMBER
        "25": I-DATE
        "26": I-DRIVERLICENSENUM
        "27": I-EMAIL
        "28": I-GENDER
        "29": I-GIVENNAME
        "30": I-IDCARDNUM
        "31": I-PASSPORTNUM
        "32": I-SEX
        "33": I-SOCIALNUM
        "34": I-STREET
        "35": I-SURNAME
        "36": I-TAXNUM
        "37": I-TELEPHONENUM
        "38": I-TIME
        "39": I-TITLE
        "40": I-ZIPCODE
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        B-AGE: 1
        B-BUILDINGNUM: 2
        B-CITY: 3
        B-CREDITCARDNUMBER: 4
        B-DATE: 5
        B-DRIVERLICENSENUM: 6
        B-EMAIL: 7
        B-GENDER: 8
        B-GIVENNAME: 9
        B-IDCARDNUM: 10
        B-PASSPORTNUM: 11
        B-SEX: 12
        B-SOCIALNUM: 13
        B-STREET: 14
        B-SURNAME: 15
        B-TAXNUM: 16
        B-TELEPHONENUM: 17
        B-TIME: 18
        B-TITLE: 19
        B-ZIPCODE: 20
        I-AGE: 21
        I-BUILDINGNUM: 22
        I-CITY: 23
        I-CREDITCARDNUMBER: 24
        I-DATE: 25
        I-DRIVERLICENSENUM: 26
        I-EMAIL: 27
        I-GENDER: 28
        I-GIVENNAME: 29
        I-IDCARDNUM: 30
        I-PASSPORTNUM: 31
        I-SEX: 32
        I-SOCIALNUM: 33
        I-STREET: 34
        I-SURNAME: 35
        I-TAXNUM: 36
        I-TELEPHONENUM: 37
        I-TIME: 38
        I-TITLE: 39
        I-ZIPCODE: 40
        O: 0
layer_norm_eps:
    value: 1e-07
learning_rate:
    value: 2e-05
legacy:
    value: true
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 100
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 512
max_relative_positions:
    value: -1
max_steps:
    value: -1
metric_for_best_model:
    value: f1
min_length:
    value: 0
model/num_parameters:
    value: 278250281
model_type:
    value: deberta-v2
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
norm_rel_ebd:
    value: layer_norm
num_attention_heads:
    value: 12
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./models/mdeberta-pii-v1
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 0
parallelism_config:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
pooler_dropout:
    value: 0
pooler_hidden_act:
    value: gelu
pooler_hidden_size:
    value: 768
pos_att_type:
    value:
        - p2c
        - c2p
position_biased_input:
    value: false
position_buckets:
    value: 256
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
relative_attention:
    value: true
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
share_att_key:
    value: true
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.0
type_vocab_size:
    value: 0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 251000
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
